### ISSUE TITLE
`alarm_control_panel` status doesn't change correctly

### ISSUE THREAD

**Issue by xtimmy86x** [palazzem/ha-econnect-alarm#108]
**Describe the bug**
When the alarm switches from any armed state to another, the status doesn't change directly to the desired one, but first transitions to "armed_away".

**Error message**

**Expected behavior**
The status should change directly to the desired one.

**Additional context**

![Screenshot_20231104_091159_Chrome](https://github.com/palazzem/ha-econnect-alarm/assets/76836856/62ba8227-6a70-42da-8913-0c2107eba53e)

**To Reproduce**
Arm the control panel from armed_night to armed_home

**Environment**
 - Operating System (OS): HAOS
 - Library version (commit or version number): 2.1.0
 - Home Assistant version: 2023.11.1
 - Last working Home Assistant release (if known):

**Comment by palazzem** [comment]
I'm also experiencing the same but to me, it's happening at every poll:

<img width="500" alt="image" src="https://github.com/palazzem/ha-econnect-alarm/assets/1560405/2a695509-0f0b-4122-9b24-4c1fd058af67">

I'm running version `2.2.0.dev1`, so probably a change made this worse.

**Comment by palazzem** [comment]
Fixed in https://github.com/palazzem/econnect-python/pull/128
