### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by parabag** [palazzem/ha-econnect-alarm#119]
**Describe the bug**
During the set up of the integration with IESS/Metronet credentials I am unable to authenticate, while I am sure that user and password are correct. Thanks for your help.

**Error message**
"invalid authentication"

**Expected behavior**
proceed with the installation of the integration

**Environment**
 - Operating System (OS): HASS in a VM
 - Library version (commit or version number): 2.2.1
 - Home Assistant version: 2023.12.2
 - Last working Home Assistant release (if known): none

**Comment by parabag** [comment]
I close this issue immediately. For anyone that encounter the same issue i had tu "default" in the domain name.

**Comment by palazzem** [comment]
Hello @parabag and thanks for reaching out! I'm happy to hear that you found the way to make it work, but feel free to provide any feedback you have (here or in Discord)! About your specific issue, we added this statement in the login form:

> In case you don't have a vendor defined, set it to `default`.

As it may not be visible enough, we would like to hear your thoughts in case you have more ideas to improve the onboarding process! One thing I may investigate is to verify if using `default` as default (meaning you don't write anything) is a good option or not. 

Anyway, feel free to give us more suggestions! We're happy to hear your thoughts to make this integration better and better over time! Thanks again!

**Comment by parabag** [comment]
Grazie Emanuele,The integration is simply fantastic, so first of all thank you.The only thing I would do is to set the domain as mandatory and not optionalCiaoLucaSent from my iPadOn 28 Dec 2023, at 20:05, Emanuele Palazzetti ***@***.***> wrote:﻿
Hello @parabag and thanks for reaching out! I'm happy to hear that you found the way to make it work, but feel free to provide any feedback you have (here or in Discord)! About your specific issue, we added this statement in the login form:

In case you don't have a vendor defined, set it to default.

As it may not be visible enough, we would like to hear your thoughts in case you have more ideas to improve the onboarding process! One thing I may investigate is to verify if using default as default (meaning you don't write anything) is a good option or not.
Anyway, feel free to give us more suggestions! We're happy to hear your thoughts to make this integration better and better over time! Thanks again!

**Comment by palazzem** [comment]
Thanks for the suggestion @parabag ! I'm opening again this issue as I want to get to the bottom of it. I think what you experienced must not happen. Very likely we can find an elegant solution that doesn't require new users to read the documentation or block of texts.

I'll keep you posted on what the solution would be!

**Comment by parabag** [comment]
Grazie!Sent from my iPhoneOn 30 Dec 2023, at 14:47, Emanuele Palazzetti ***@***.***> wrote:﻿
Thanks for the suggestion @parabag ! I'm opening again this issue as I want to get to the bottom of it. I think what you experienced must not happen. Very likely we can find an elegant solution that doesn't require new users to read the documentation or block of texts.
I'll keep you posted on what the solution would be!
