### ISSUE TITLE
Aggiornamento dei sensori

### ISSUE THREAD

**Issue by Riky161** [palazzem/ha-econnect-alarm#170]
Mi succede spesso che l’aggiornamento dei sensori non mi si aggiorna nonostante abbia provato anche ad abbassare il tempo di refresh; funziona per un po’ dopo aver ricaricato l’applicazione ma dopo va come in dormienza e non mi cambia più lo stato dei sensori presenti.

**Comment by palazzem** [comment]
Ciao @Riky161 , e grazie per la segnalazione! Avrei bisogno di maggiori informazioni per comprendere meglio il problema che stai verificando, in particolare:

1. Quale versione di Home Assistant stai utilizzando?
2. Quale versione dell'integrazione e-connect stai utilizzando?
3. L'hai installata tramite HACS, oppure manualmente?
4. Quale intervallo hai impostato?

Inoltre, se possibile, dovresti inviarmi dei log di debug che puoi attivare, registrare e salvare [seguendo i passaggi descritti](https://github.com/palazzem/ha-econnect-alarm?tab=readme-ov-file#troubleshooting) nel README di progetto.

Ricordati che la modalità debug potrebbe esporre informazioni che non vuoi diffondere pubblicamente, pertanto dovresti leggere il file prima di inviarlo come allegato. In alternativa, puoi unirti al nostro [canale Discord](https://discord.gg/NSmAPWw8tE) e contattarmi direttamente tramite messaggio privato (sono sempre `@palazzem`).

Grazie in anticipo per il tempo speso nel rispondere alle mie domande per riuscire a migliorare l'integrazione grazie al tuo feedback!

**Comment by palazzem** [comment]
Ah dimenticavo, se non avessi tempo a disposizione per inviare i log di debug, nel frattempo puoi rispondere alle 4 domande indicate in quanto potrei già scoprire qualcosa di utile! Grazie in anticipo!

**Comment by Riky161** [comment]
Questa la versione di home assistant Comunque l’ho installata da Hacs ed era l’ultima versione…. Forse ho sbagliato ed ho installato quella per sviluppatori. Infatti disinstallandola e installando l’ultima versione e Connect 2.4.1 a1 tutto va alla perfezione.Scusa ma non sono molto pratico… spero di non averti arrecato disturbo.Comunque prima di disinstallarla avevo provato anche a modificare con vari tempi di intervallo ma non cambiava nulla… Inviato da iPhoneIl giorno 24 ago 2024, alle ore 09:39, Emanuele Palazzetti ***@***.***> ha scritto:﻿
Ah dimenticavo, se non avessi tempo a disposizione per inviare i log di debug, nel frattempo puoi rispondere alle 4 domande indicate in quanto potrei già scoprire qualcosa di utile! Grazie in anticipo!

**Comment by palazzem** [comment]
Grazie @Riky161 per il feedback e sono contento che l'integrazione sia tornata a funzionare! Dunque, provo a fare un pò di chiarezza in quanto non hai commesso alcun errore!

- La versione da te installata via HACS, è probabilmente la 2.4.0 (l'ultima versione ufficiale) ed è la versione dove riscontri il bug da te indicato.
- Successivamente, potresti aver attivato le versioni "Beta" via HACS e probabilmente hai installato la versione 2.4.1.a1 (versione Alpha 1).
- La versione Alpha 1 deve includere un fix che risolve appieno il bug da te individuato, tuttavia queste modifiche sono presenti solo in questa versione e non in quella ufficiale.

Questa è una buona notizia, in quanto significa che non appena rilascerò la nuova versione il tuo problema sarà risolto! Tuttavia, preferisco non chiudere questo issue da te aperto in quanto quando rilascerò una versione ufficiale, dovresti disattivare il canale "Beta" da HACS e cambiare versione (ci penserò io ad indicarti quale). La ragione è che facendo esperimenti, potresti automaticamente installare una versione non più funzionante.

Per farla breve: sono contento che il problema è risolto, ti contatterò in futuro per chiederti di installare un'altra versione con il tuo fix incluso!

> Scusa ma non sono molto pratico… spero di non averti arrecato disturbo

Assolutamente no! Scrivi ogni volta che hai un dubbio o un problema! Il fatto che stai utilizzando la mia integrazione è una grande soddisfazione per me! Grazie ancora!

**Comment by Riky161** [comment]
Si è andata esattamente come hai capito tu….Grazie ancora per il lavoro che hai fatto e che fai…. È un’ottima integrazione e fa la differenza su home assistant…. Il giorno 24 ago 2024, alle ore 13:35, Emanuele Palazzetti ***@***.***> ha scritto:﻿
Grazie @Riky161 per il feedback e sono contento che l'integrazione sia tornata a funzionare! Dunque, provo a fare un pò di chiarezza in quanto non hai commesso alcun errore!

La versione da te installata via HACS, è probabilmente la 2.4.0 (l'ultima versione ufficiale) ed è la versione dove riscontri il bug da te indicato.
Successivamente, potresti aver attivato le versioni "Beta" via HACS e probabilmente hai installato la versione 2.4.1.a1 (versione Alpha 1).
La versione Alpha 1 deve includere un fix che risolve appieno il bug da te individuato, tuttavia queste modifiche sono presenti solo in questa versione e non in quella ufficiale.

Questa è una buona notizia, in quanto significa che non appena rilascerò la nuova versione il tuo problema sarà risolto! Tuttavia, preferisco non chiudere questo issue da te aperto in quanto quando rilascerò una versione ufficiale, dovresti disattivare il canale "Beta" da HACS e cambiare versione (ci penserò io ad indicarti quale). La ragione è che facendo esperimenti, potresti automaticamente installare una versione non più funzionante.
Per farla breve: sono contento che il problema è risolto, ti contatterò in futuro per chiederti di installare un'altra versione con il tuo fix incluso!

Scusa ma non sono molto pratico… spero di non averti arrecato disturbo

Assolutamente no! Scrivi ogni volta che hai un dubbio o un problema! Il fatto che stai utilizzando la mia integrazione è una grande soddisfazione per me! Grazie ancora!

**Comment by palazzem** [comment]
Ciao @Riky161 ! Non so se hai mai più riscontrato il problema da te indicato, tuttavia volevo informarti che abbiamo rilasciato una nuova versione `2.4.1` che include tutte le ultime modifiche (https://github.com/palazzem/ha-econnect-alarm/releases/tag/v2.4.1)

Per il momento considero questo bug risolto, ma riaprilo pure qualora non fosse il caso!
