### ISSUE TITLE
Add an official icon

### ISSUE THREAD

**Issue by palazzem** [palazzem/ha-econnect-alarm#47]
**Is your feature request related to a problem? Please describe.**

Currently the integration is not showing any icon. We should provide an icon to represent the e-Connect cloud.

**Describe the solution you'd like**

Prepare an e-Connect icon and add it to official repository: https://github.com/home-assistant/brands

**Describe alternatives you've considered**

n/a

**Additional context**

We should take in consideration that we support also IESS, so we should pay attention to what icon are we adding there.

**Comment by xtimmy86x** [comment]
For my personal opinion, is good to use the "Elmo" icon because is the Main brand of Elmo and IESS brands

**Comment by palazzem** [comment]
Yeah, I was also thinking to use the e-Connect one, that is not related to a brand but more to the technology.

Example:
<img width="89" alt="image" src="https://github.com/palazzem/ha-econnect-alarm/assets/1560405/21bc2e75-c0e4-416a-a3dc-36a591e56a3c">

Actually, it looks like it is the icon used in Alexa / Google Home, so maybe it could be a good option (source: https://www.amazon.it/EL-MO-S-p-A-e-Connect/dp/B07SM9PLZ9)!

**Comment by xtimmy86x** [comment]
> Yeah, I was also thinking to use the e-Connect one, that is not related to a brand but more to the technology.
> 
> Example: <img alt="image" width="89" src="https://user-images.githubusercontent.com/1560405/270620054-21bc2e75-c0e4-416a-a3dc-36a591e56a3c.png">
> 
> Actually, it looks like it is the icon used in Alexa / Google Home, so maybe it could be a good option (source: https://www.amazon.it/EL-MO-S-p-A-e-Connect/dp/B07SM9PLZ9)!

Is a good idea but for my opinion  the integration is called Elmo/IESS alarm so the icon/logo should follow this line

**Comment by palazzem** [comment]
Cool, let's ask the community over Discord and let's see what they think! that should be a no-brainer to implement after!

**Comment by palazzem** [comment]
We decided to move forward with the e-Connect icon and then renaming the integration as "e-Connect/Metronet Alarm" (the integration domain will become `econnect_metronet_alarm`).

**Comment by xtimmy86x** [comment]
If we use a mixed icon like this?

![e-Connect-1](https://github.com/palazzem/ha-econnect-alarm/assets/76836856/73fc63cf-2444-4034-9924-c91873289a31)

**Comment by xtimmy86x** [comment]
![econnect-metronet2](https://github.com/palazzem/ha-econnect-alarm/assets/76836856/7d07a05f-286d-4d70-9bc3-cb4751d6a8d5)

With the square form it turns out like this, don't look at the black outline, it's for illustration purposes only

**Comment by palazzem** [comment]
That sounds great! if you want you can share it in the Discord channel and gather further feedback!

**Comment by xtimmy86x** [comment]
![Screenshot 2023-10-01 094743aaa](https://github.com/palazzem/ha-econnect-alarm/assets/76836856/a2fcf433-e935-4bab-bf9c-dad2d3916e72)

This is the landscape version of the logo
If is ok for you i proceed with the creation of the necessary files

**Comment by palazzem** [comment]
@xtimmy86x I'd say this is perfect! impressive job! whenever you have time, feel free to share all the assets so I can create the PR in https://github.com/home-assistant/brands (of course I'll tag you to give you credits for this great work!)

**Comment by palazzem** [comment]
Icons have been published in https://github.com/home-assistant/brands/pull/4750 and the CDN has been reset as planned. This task is now closed, thank you very much @xtimmy86x for the work on the icons!
