### ISSUE TITLE
Integration config form: replace text inputs with entity lookup widgets

### ISSUE THREAD

**Issue by davidecavestro** [palazzem/ha-econnect-alarm#60]
**Is your feature request related to a problem? Please describe.**
As a user I don't like setting numeric IDs to relate sectors with arm mode (i.e. setting _2,3,4_ on the _areas_arm_home_ field and son on).

**Describe the solution you'd like**
I'd prefer selecting sectors from the list of available ones on my current system

**Describe alternatives you've considered**
Discussed on Discord.

**Additional context**

This is how it currently works 
![image](https://github.com/palazzem/ha-econnect-alarm/assets/447917/77f96f6a-7e21-4c70-910f-bb1f48847c0d)

This is how I'd like to set it up (simulated using the _Add group_ UI feature)
![image](https://github.com/palazzem/ha-econnect-alarm/assets/447917/efb4f0ee-67f8-496d-9e5e-fe4f9f4c8ad0)

**Comment by palazzem** [comment]
When we work on this functionality, let's keep in consideration to include Alarm AWAY configuration (related to: https://github.com/palazzem/ha-econnect-alarm/issues/96)

**Comment by palazzem** [comment]
@xtimmy86x assigning this to you!
